INSERT INTO Sites (site_name, region) VALUES
('wellington central', 'wellington'),
('auckland north', 'auckland'),
('christchurch east', 'canterbury'),
('hamilton city', 'waikato'),
('napier port', 'hawkes bay'),
('nelson lakes', 'nelson'),
('queenstown hill', 'otago'),
('invercargill park', 'southland'),
('rotorua geothermal', 'bay of plenty'),
('whangarei heads', 'northland'),
('tauranga coast', 'bay of plenty'),
('palmerston north central', 'manawatu-wanganui'),
('new plymouth heights', 'taranaki'),
('gisborne coast', 'gisborne'),
('dunedin south', 'otago'),
('blenheim vineyards', 'marlborough'),
('westport harbour', 'west coast'),
('timaru port', 'canterbury'),
('greymouth east', 'west coast'),
('wanaka hills', 'otago');
